### ISSUE TITLE
Dotted notation handling

### ISSUE THREAD

**Issue by vincentni** [aws/eks-anywhere-packages#299]
**What happened**:
The current code doesn't handle dotted notations from `config` section in a package spec file correctly. It treats the whole dotted notation as a key, while the official Helm code breaks it down and treats it as a nested map.

For example, `expose.tls.certSource: auto` results in the following:

Helm code:
![image](https://user-images.githubusercontent.com/1473081/176718789-f4fbf735-327e-46a7-8e16-0097ba6e1965.png)

Our code:
![image](https://user-images.githubusercontent.com/1473081/176719176-ea92f136-3baa-460b-b54b-9a18a75bd5c4.png)

The discrepancy results in no value override in those dotted-notation fields, because Helm relies on keys for value coalescing. More details for value coalescing can be found [here](https://github.com/helm/helm/blob/db2485b20c8f53d802f4fc98c2f95e1fc0460d15/pkg/chartutil/coalesce.go#L156-L188).

**What you expected to happen**:
Treat those dotted notations as nested maps, the same way Helm handles.

**How to reproduce it (as minimally and precisely as possible)**:
Sample package spec:
```yaml
apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: Package
metadata:
  name: test
  namespace: eksa-packages
spec:
  config: |
    expose.tls.certSource: "auto"
    secretKey: "use-a-secret-key"
  packageName: harbor
```

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by TerryHowe** [comment]
maybe

```
apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: Package
metadata:
  name: test
  namespace: eksa-packages
spec:
  config: |
    expose:
       tls:
         certSource: "auto"
    secretKey: "use-a-secret-key"
  packageName: harbor

**Comment by vincentni** [comment]
If I change the package spec to the following, it works
```yaml
apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: Package
metadata:
  name: test
  namespace: eksa-packages
spec:
  config: |
    expose:
        tls:
          certSource: "auto"
    secretKey: "use-a-secret-key"
  packageName: harbor
```

Closing this as the issue is now with the CLI part that generates a malformed package spec file.
