### ISSUE TITLE
Incorrect package bundle format with multiple versions for packages

### ISSUE THREAD

**Issue by vincentni** [aws/eks-anywhere-packages#320]
**What happened**:
The format of the generated package bundle is incorrect when multiple versions are specified for a package.

**How to reproduce it (as minimally and precisely as possible)**:
* input file:
```
# This info is hardcoded and comes from https://github.com/aws/eks-anywhere-build-tooling
name: "v1-21-1001"
kubernetesVersion: "1.21"
packages:
  - org: harbor
    projects:
      - name: harbor
        repository: harbor/harbor-helm
        registry: public.ecr.aws/y8n6a2y0
        versions:
            - name: latest
            - name: 2.5.1-ccd724a0a27cc863553fad5eace915086febe5bd
```
* output file:
```
apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: PackageBundle
metadata:
  annotations:
    eksa.aws.com/excludes: LnNwZWMucGFja2FnZXNbXS5zb3VyY2UucmVnaXN0cnkKLnNwZWMucGFja2FnZXNbXS5zb3VyY2UucmVwb3NpdG9yeQo=
    eksa.aws.com/signature: MEUCICl0owRFfZPn/gDr0hN+xWQvU5dF9JnwHGAGuohkCB43AiEAz73wqyFS9K3lmOb7/Gg4L9hzuaM2Fkp3kiS88XkonM0=
  name: v1-21-1001
  namespace: eksa-packages
spec:
  packages:
  - name: harbor
    source:
      repository: harbor/harbor-helm
      versions:
      - configurations:
        - default: ""
          name: sourceRegistry
          required: false
        - default: https://127.0.0.1:30003
          name: externalURL
          required: false
        - default: IfNotPresent
          name: imagePullPolicy
          required: false
        - default: info
          name: logLevel
          required: false
        - default: Harbor12345
          name: harborAdminPassword
          required: false
        - default: ""
          name: secretKey
          required: true
        - default: nodePort
          name: expose.type
          required: false
        - default: "true"
          name: expose.tls.enabled
          required: false
        - default: secret
          name: expose.tls.certSource
          required: false
        - default: ""
          name: expose.tls.auto.commonName
          required: false
        - default: harbor-tls-secret
          name: expose.tls.secret.secretName
          required: false
        - default: harbor
          name: expose.nodePort.name
          required: false
        - default: "80"
          name: expose.nodePort.ports.http.port
          required: false
        - default: "30002"
          name: expose.nodePort.ports.http.nodePort
          required: false
        - default: "443"
          name: expose.nodePort.ports.https.port
          required: false
        - default: "30003"
          name: expose.nodePort.ports.https.nodePort
          required: false
        - default: harbor
          name: expose.loadBalancer.name
          required: false
        - default: ""
          name: expose.loadBalancer.IP
          required: false
        - default: "80"
          name: expose.loadBalancer.ports.httpPort
          required: false
        - default: "30002"
          name: expose.loadBalancer.ports.httpsPort
          required: false
        - default: "true"
          name: internalTLS.enabled
          required: false
        - default: keep
          name: persistence.resourcePolicy
          required: false
        - default: 5Gi
          name: persistence.persistentVolumeClaim.registry.size
          required: false
        - default: ""
          name: persistence.persistentVolumeClaim.registry.storageClass
          required: false
        - default: 1Gi
          name: persistence.persistentVolumeClaim.jobservice.size
          required: false
        - default: ""
          name: persistence.persistentVolumeClaim.jobservice.storageClass
          required: false
        - default: 1Gi
          name: persistence.persistentVolumeClaim.database.size
          required: false
        - default: ""
          name: persistence.persistentVolumeClaim.database.storageClass
          required: false
        - default: 1Gi
          name: persistence.persistentVolumeClaim.redis.size
          required: false
        - default: ""
          name: persistence.persistentVolumeClaim.redis.storageClass
          required: false
        digest: sha256:8fc4e42ed5660c3e3226c2a7cafab17347d2e6803f780627037800f65fdcfa48
        images:
        - digest: sha256:f8448e8ea490ef26bbf09e4007de543fad9108492b2fcd2fba509a4217ce2c36
          repository: harbor/harbor-core
        - digest: sha256:4f244ec23a1b67a337a7a2ca7a10c82db98c3b4af1b1d08e3260ae9a9bb967bd
          repository: harbor/harbor-db
        - digest: sha256:8ec07c7dbffcfb81c188a54233ce59a9cbaf5dfdf432739b6467ff046af5c5c7
          repository: harbor/harbor-exporter
        - digest: sha256:2eaa4331e801ff04497e779a161e1ddc52bdeb1fe48d8e690080eb9aaefb40ec
          repository: harbor/harbor-jobservice
        - digest: sha256:6f0743da4210260008085fb0ce4773599da4b675086ee1ad12d1ca4326bb4a89
          repository: harbor/harbor-nginx
        - digest: sha256:fdad56c1f836710460ba3e90ec0f13125d490acf0d78b185b56a3d9fa6e55291
          repository: harbor/harbor-portal
        - digest: sha256:e6778eb8b51b5bfbaf111571dd00e9cf75be33f0602e6b55159a4383034c80d7
          repository: harbor/harbor-redis
        - digest: sha256:7b7b2d60079ec25a7205b396df6b51ae0aa850ee7af363a17840ce90a8bf0896
          repository: harbor/harbor-registry
        - digest: sha256:adc3f25040b9d1a64a911f5a33ec8f2df9a459a7fa0d5ffd31e60b6ed937e4a6
          repository: harbor/harbor-registryctl
        - digest: sha256:be3d8dabd429c76a325634b207e4459b55953d849e70b598aa61884985e0ed61
          repository: harbor/harbor-trivy
        name: 2.5.1-1ededc2a86e772d02875796fa619e1a6382727dc
      - digest: sha256:4faca7f6bb22782c7abc5461baea58ef0b6db106f58178445cb7042a217d3bb5
        name: 2.5.1-ccd724a0a27cc863553fad5eace915086febe5bd
```
