### ISSUE TITLE
MetalLB packages using a packageSecret for BGPPeers do not pass validation

### ISSUE THREAD

**Issue by cryptk** [aws/eks-anywhere-packages#600]
**What happened**:
Attempted to deploy MetalLB via EKS-A Packages while referencing a passwordSecret, which is valid for a MetalLB BGPPeer spec per https://metallb.universe.tf/apis/#metallb.io/v1beta2.BGPPeer.  Received the following error:

`admission webhook "vpackage.kb.io" denied the request: package metallb failed validation with error: error validating configurations - BGPPeers.0: Additional property passwordSecret is not allowed`

**What you expected to happen**:
MetalLB should be deployed using BGPPeers that utilize a passwordSecret rather than a password embedded directly in the BGPPeer config

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: Package
metadata:
  name: generated-metallb
  namespace: eksa-packages-workload-cluster
spec:
  packageName: metallb
  config: |
    IPAddressPools:
      - name: default
        addresses:
          - 192.168.1.50-192.168.1.59
    BGPAdvertisements:
      - ipAddressPools:
        - default
    BGPPeers:
      - peerAddress: 192.168.1.250
        peerASN: 65100
        myASN: 65200
        passwordSecret: aSecretName
```

**Anything else we need to know?**:
I understand that this configuration when using a management cluster will require that a secret be created on the workload cluster, and then the metallb package deployed onto that workload cluster via the management cluster, which is a bit more of an advanced config, but it would allow for proper separation of secrets/credentials from configuration.

Additionally, when using tooling to deploy Curated Packages, the current requirement to embed the password within the MetalLB package definition results in credential information being logged and displayed in the tooling logs Ref: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1728.  Allowing the use of a passwordSecret rather than embedding the password directly would resolve this knock-on effect as well.

**Environment**:
- EKS Anywhere Release: v0.12.0
- EKS Distro Release: 1.22
